#!/usr/bin/env python3
# -*- coding: utf-8 -*-

DATASETS_PATH = "./datasets/most/"
DATA_DOWNLOAD_LIST = "./datasets/most/cadcUrlList_test.txt"

COLUMNS = [
    "[DEGREES] LONGITUDE OF SATELLITE",
    "[DEGREES] LATITUDE OF SATELLITE",
    "[M] ALTITUDE OF SATELLITE",
    "[DEGREES] ANGLE TO EARTH LIMB",
    "[DEGREES] NADIR RIGHT ASCENSION",
    "[DEGREES] NADIR DECLINATION",
    "[DEGREES] NADIR LONGITUDE",
    "[DEGREES] NADIR LATITUDE",
    "[DEGREES] SOLAR RIGHT ASCENSION",
    "[DEGREES] SOLAR DECLINATION",
    "[DEGREES] SOLAR ALTITUDE",
    "[DEGREES] SOLAR AZIMUTH",
    "[DEGREES] SOLAR LONGITUDE",
    "[DEGREES] SOLAR LATITUDE",
    "[DEGREES] LUNAR RIGHT ASCENSION",
    "[DEGREES] LUNAR DECLINATION",
    "[DEGREES] LUNAR ALTITUDE",
    "[DEGREES] LUNAR AZIMUTH",
    "[DEGREES] LUNAR LONGITUDE",
    "[DEGREES] LUNAR LATITUDE",
    "[DEGREES] LUNAR-TARGET ANGULAR SEPERATION",
    "[nT] MAGNETIC FIELD STRENGTH",
]

CATEGORICAL_FEATURES = [
    "[DEGREES] SOLAR ALTITUDE",
    "[DEGREES] SOLAR AZIMUTH",
    "[DEGREES] SOLAR LONGITUDE",
]

TARGET_FEATURE = "[nT] MAGNETIC FIELD STRENGTH"
